### ISSUE TITLE
include shtool dep

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-cli#4]
On OSX autogen fails with:

```
src/Makefile.am:34: but option 'subdir-objects' is disabled
src/Makefile.am:34: warning: source file '$(top_srcdir)/ed25519/src/verify.c' is in a subdirectory,
src/Makefile.am:34: but option 'subdir-objects' is disabled
src/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
./autogen.sh: line 30: shtoolize: command not found
```

It would be cool to have shtoolize included as dep or if that is not possible some docs how to install it.

**Comment by davide-scola** [comment]
`grenache-cli` is not directly dependent on [GNU shtool](https://www.gnu.org/software/shtool/); it is part of the build system like the others _autotools_: `autoconf`, `automake`, etc.

You do not have to clone the repository if you want to install `grenache-cli`: in that case, please download the _source code distribution_ (the `.tar.xz` file that you get from the [releases](https://github.com/bitfinexcom/grenache-cli/releases) section) and you are ready to go without the need for external tools. Anyone who checks `grenache-cli` code out of git in order to build it should be expected to have proper development tools installed (like any other project using _autotools_).

That said, you can safely ignore the warning as it is a non-blocking error: the `shtool` script is used only to generate strings in bold when running `configure`. The missing script does not prevent `configure` from running: however, [this link may help you](https://tinyurl.com/ydgzwnfe) :-)

I'm closing this as it's not an issue of `grenache-cli`, let me know if you need more information.
